In [346]:
import pandas as pd
import numpy as np
from scipy.special import softmax
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification,AutoModelForCausalLM
import torch


In [ ]:
# Load the Excel file
file_path = r'C:/Users/Work/OneDrive/Desktop/Document1.xlsx'
df = pd.read_excel(file_path)
df.columns = ['S_ID', 'ConcatenatedResponse']

In [ ]:
df

In [ ]:
df['concatenatedResponse letter count']=df['ConcatenatedResponse'].apply(len)

In [ ]:
df.iloc[df['concatenatedResponse letter count'].idxmax()][1]

In [ ]:
#text preprocessing Data
df['ConcatenatedResponse'][3]

In [ ]:
#import string 
#string.punctuation

In [ ]:
import nltk



In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

In [ ]:
stopwords.words('arabic')

In [ ]:
print(stopwords.words('arabic'))

In [ ]:
s=df['ConcatenatedResponse'][0]
s


In [ ]:
import re

In [ ]:
re.sub('أ-ى ^', " ",s)

In [ ]:
def custom_split(text, delimiter=' '):
    result = []
    current_word = ''
    
    for char in text:
        if char == delimiter:
            result.append(current_word)
            current_word = ''
        else:
            current_word += char
    
    if current_word:
        result.append(current_word)
    
    return result


In [ ]:
s=custom_split(s)
s

In [ ]:
from nltk.corpus import stopwords


In [ ]:
tem = []
for word in s:
    if word not in stopwords.words('arabic'):
        tem.append(word)

tem

In [ ]:
[word for word in s if word not in stopwords.words('arabic') ]

In [ ]:
s= ' '.join(tem)
s

In [ ]:
from nltk.stem import ISRIStemmer
LS= ISRIStemmer()

In [374]:
s=LS.stem(s)
s

' الذى اعجبنى  شيء يعجبني والذى يعجبنى شيء ومقتراحات تحسينى هى شيء بالفعل'

In [376]:
from sklearn.feature_extraction.text import CountVectorizer 

In [378]:
cv=CountVectorizer()

In [380]:
cv.fit_transform(s.split()).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [391]:
corpus = []
for i in range(len(df)):
    s = re.sub('[ا-ى-ى]', " ", df['ConcatenatedResponse'][i])
    s = custom_split(s)
    s = [word for word in s if word not in stopwords.words('arabic')]
    s = ' '.join(s)
    s = LS.stem(s)
    corpus.append(s)


corpus


['                                              ',
 '                                              ',
 '                                                         ',
 '                                              ',
 '                                              ',
 '                                                   ',
 '                                                  ',
 '                                              ',
 '                                              ',
 '                                              ',
 '                                              ',
 '                                              ',
 '                                              ',
 '                                              ',
 '                                             يء                       ',
 '                 يء                                 ',
 '                                                                                     ',
 '                                          

In [419]:
corpus = []
for i in range(len(df)):
    s = df['ConcatenatedResponse'][i]
    
    # Step 1: Replace specific characters
    s = re.sub('[ - ^]', ' ', s)  # Removed ا and ى from the pattern
    # Step 2: Custom split
    s = custom_split(s)
    # Step 3: Remove stopwords
    s = [word for word in s if word not in stopwords.words('arabic')]
    # Step 4: Join words back into a string
    s = ' '.join(s)
    # Step 5: Stem the words
    s = stemmer.stem(s)
    
    # Append to corpus
    corpus.append(s)

corpus

[' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى شي والذى يعجبنى شي ومقتراحات تحسينى هى يوجد',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى أعجبني والذى يعجبنى شئ ومقتراحات تحسينى هى',
 ' الذى اعجبنى اعجبني والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى  والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى معرفة تعاليم الدين والذى يعجبنى لاشيء ومقتراحات تحسينى هى يوجد',
 ' الذى اعجبنى شيء والذى يعجبنى  ومقتراحات تحسينى هى',
 ' الذى اعجبنى شرح الدكتور والمقرر وموضوعاته والذى يعجبنى يوجد ومقتراحات تحسينى هى يوجد',
 ' الذى اعجبنى  والذى يع

In [421]:
cv=CountVectorizer()

In [431]:
cv.fit_transform(corpus).toarray().shape

(73, 119)

In [435]:
x=cv.fit_transform(corpus).toarray()
x


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [439]:
# Load the Excel file
file_path = r'C:/Users/Work/OneDrive/Desktop/Document2 (2).xlsx'
sentiment = pd.read_excel(file_path)
sentiment.columns = ['S_ID', 'ConcatenatedResponse','Sentiment']
sentiment 

S_ID                               ConcatenatedResponse Sentiment
0      1   الذى اعجبنى  والذى لم يعجبنى  ومقتراحات تحسين...    محايد 
1     39   الذى اعجبنى  والذى لم يعجبنى  ومقتراحات تحسين...    محايد 
2     51   الذى اعجبنى كل شي والذى لم يعجبنى لا شي ومقتر...    ايجابى
3     85   الذى اعجبنى  والذى لم يعجبنى  ومقتراحات تحسين...    محايد 
4    114   الذى اعجبنى  والذى لم يعجبنى  ومقتراحات تحسين...    محايد 
..   ...                                                ...       ...
68  2255   الذى اعجبنى جيد مستوفي جدا للماده العلميه للد...    ايجابى
69  2256   الذى اعجبنى  والذى لم يعجبنى  ومقتراحات تحسين...    محايد 
70  2257   الذى اعجبنى شرح الدكتور المبسط والذى لم يعجبن...    ايجابى
71  2258   الذى اعجبنى شرح الدكتور واسلوبه والذى لم يعجب...    ايجابى
72  2260   الذى اعجبنى  كل شيء يعجبني والذى لم يعجبنى لا...   ايجابى 

[73 rows x 3 columns]

In [21]:
def summarize_text(text):
    try:
        inputs = tokenizer_sum.encode("summarize: " + text, return_tensors='pt', max_length=512, truncation=True).to(device)
        summary_ids = model_sum.generate(inputs, max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)
        summary = tokenizer_sum.decode(summary_ids[0], skip_special_tokens=True)
    except Exception as e:
        print(f"Error summarizing text: {text}, error: {e}")
        summary = "Error in summarization"
    return summary

In [447]:
y=sentiment['Sentiment']
y

0      محايد 
1      محايد 
2      ايجابى
3      محايد 
4      محايد 
       ...   
68     ايجابى
69     محايد 
70     ايجابى
71     ايجابى
72    ايجابى 
Name: Sentiment, Length: 73, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split


In [451]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=42)

In [453]:
x_train.shape

(48, 119)

In [455]:
x_test.shape

(25, 119)

In [489]:
# Building the model
from sklearn.naive_bayes import GaussianNB

In [491]:
clf=MultinomialNB()

In [493]:
clf.fit(x_train,y_train)

MultinomialNB()

In [495]:
# Model Prediction 


In [497]:
y_pre=clf.predict(x_test)
y_pre

array(['محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ',
       'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ', 'إيجابى ',
       'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ',
       'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ',
       'محايد '], dtype='<U7')

In [499]:
y_test.values

array(['محايد ', 'محايد ', 'محايد ', 'محايد ', 'محايد ', 'ايجابى ',
       'محايد ', 'محايد ', 'محايد ', 'ايجابى', 'ايجابى', 'إيجابى ',
       'محايد ', 'محايد ', 'ايجابى', 'إيجابى ', 'محايد ', 'سلبى',
       'محايد ', 'محايد ', 'ايجابى', 'إيجابى', 'ايجابى', 'محايد ',
       'محايد '], dtype=object)

In [501]:
#Model Evaluation 

In [503]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [505]:
print(confusion_matrix(y_test,y_pre))

[[ 0  0  0  0  0  1]
 [ 0  1  0  0  0  1]
 [ 0  0  0  0  0  5]
 [ 0  0  0  0  0  1]
 [ 0  0  0  0  0  1]
 [ 0  0  0  0  0 15]]


In [507]:
print(accuracy_score(y_test,y_pre))

0.64


In [509]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

      إيجابى       0.00      0.00      0.00         1
     إيجابى        1.00      0.50      0.67         2
      ايجابى       0.00      0.00      0.00         5
     ايجابى        0.00      0.00      0.00         1
        سلبى       0.00      0.00      0.00         1
      محايد        0.62      1.00      0.77        15

    accuracy                           0.64        25
   macro avg       0.27      0.25      0.24        25
weighted avg       0.46      0.64      0.51        25



C:\Users\Work\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Work\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Work\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [23]:
#Model Deployment& Production 


In [511]:
import joblib

In [517]:
joblib.dump(clf, 'Feedback.pkl')


['Feedback.pkl']

ImportError: cannot import name 'AutoModelForSequenceClassificationTrainer' from 'transformers' (C:\Users\Work\anaconda3\Lib\site-packages\transformers\__init__.py)